CustomCheckbox
daemabnb/Daema-BnB-front pull request #19
Opened 2019-04-29 05:53 UTC by khg0712

resolve #13

2019-04-29 06:07 UTC, engolder requested changes

2019-04-29 06:07 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  onToggleCheckbox: () => void;
체크박스의 값이 바뀔 때 마다 이벤트를 주는 것 같은데, check 여부를 불린 값으로 반환해주는 편이 좋을 것 같네요

2019-04-29 06:07 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  onToggleCheckbox: () => void;
onToggleCheckbox보다 onChange가 나을 것 같아요
먼저 Checkbox라는 이름은 이미 컴포넌트 명으로 표현되니 생략하는 편이 좋고, onToggle과 onChange 에서는 버튼을 말하는 toggle보다 값이 '바뀌었다'는 뜻에서 onChange가 낫다는 의견입니다

2019-04-29 06:07 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  },
label은 안쓰이나요?

2019-04-29 06:07 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomCheckbox.tsx
> +      <Text style={{ ...StyleSheet.flatten({ color: labelColor }) }}>{label}</Text>
styles object에 넣는 대신 flatten을 사용하신 이유가있나요?

2019-04-29 08:01 UTC, khg0712 commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  onToggleCheckbox: () => void;
onToggleCheckbox의 내부 로직은 setState를 통해서 해당 컴포넌트를 사용하는 페이지 내부의 상태를 변경하는 것이라서 리턴 값은 없어야 합니다.

2019-04-29 08:07 UTC, khg0712 commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  onToggleCheckbox: () => void;
함수 이름의 변경에는 동의합니당

2019-04-29 08:08 UTC, khg0712 commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  },
없애도록 하겠습니당

2019-04-29 08:26 UTC, khg0712 commented on daemaBnb/src/components/CustomCheckbox.tsx
> +      <Text style={{ ...StyleSheet.flatten({ color: labelColor }) }}>{label}</Text>
원래는 기존의 styles.label과 합치려고 했는데 label의 style이 사라져서 저렇게 사용할 필요가 없어졌네용 수정했습니다.

2019-05-08 00:07 UTC, engolder commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  onToggleCheckbox: () => void;
말을 잘못했네요 반환이 아니라 인자로 주어야한다는 것을 말하고싶었습니다.
`onToggleCheckbox: (value: boolean) => void;`

2019-05-08 00:08 UTC, khg0712 commented on daemaBnb/src/components/CustomCheckbox.tsx
> +  onToggleCheckbox: () => void;
오 그렇게 하면 같은 인자일때 똑같은 결과가 나오니까 좋을 것 같네용

2019-05-08 05:49 UTC, engolder approved these changes

2019-05-08 05:52 UTC, merged