ADD Divider
daemabnb/Daema-BnB-front pull request #20
Opened 2019-04-29 06:32 UTC by khg0712

resolve #10

2019-05-01 00:34 UTC, engolder requested changes
만약 공통 컴포넌트에서 custom이라는 prefix를 붙이기로 했다면 모두 통일하는 편이 좋을 것 같습니다.
CustomDivider

2019-05-01 00:34 UTC, Joonmo-dev commented on daemaBnb/src/components/Divider.tsx
> +    <View style={StyleSheet.flatten([styles.divider, { borderBottomColor: color }]) }/>
flatten을 사용하는 코드는 인라인이아니라 따로 분리하는 편이 좋을 것 같습니다.

2019-05-01 00:34 UTC, Joonmo-dev commented on daemaBnb/src/components/Divider.tsx
> +    <View style={StyleSheet.flatten([styles.divider, { borderBottomColor: color }]) }/>
props.color에따라 동적으로 스타일이 변하는데 코드 가독성을 위해 함수로 분리하면 좋을 것 같네요

2019-05-01 00:34 UTC, Joonmo-dev commented on daemaBnb/src/components/Divider.tsx
> +  color?: string;
디자인에서 여러 색상이 사용되었나요? 만약 색상이 하나였다면 고정해주세요

2019-05-08 05:35 UTC, khg0712 commented on daemaBnb/src/components/Divider.tsx
> +    <View style={StyleSheet.flatten([styles.divider, { borderBottomColor: color }]) }/>
styled component로 고정된 스타일을 만들었습니다.

2019-05-08 05:51 UTC, engolder approved these changes

2019-05-08 06:13 UTC, merged