ADD CustomeDatePresenter
daemabnb/Daema-BnB-front pull request #21
Opened 2019-05-01 00:09 UTC by khg0712

resolves #5

2019-05-01 00:24 UTC, engolder requested changes

2019-05-01 00:24 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomDatePresenter.tsx
> +const dateFormatter = (start: Date, end: Date): string => {
dateFormatter보다 formatDate가 좋을 듯 합니다 함수니깐 동사로!

2019-05-01 00:24 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomDatePresenter.tsx
> +  endDate: Date;
Date객체보다 millisecond를 받는게 좋을 것같네요. 서버로부터 시간을 받아와서 이 컴포넌트에 시간을 넣어주는데, 그렇다면 중간에 Date객체를 생성하는 코드가 들어간다는 이야기인 것 같네요. 단순히 시간을 표현하기 위해서는 Date객체로 만들지 않고 밀리세컨트를 넘겨줘도 수식으로 계산이 가능하기때문에 millisecond를 받는 것이 성능면에서, 재사용성면에서 좋을 것 같습니다

2019-05-01 00:24 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomDatePresenter.tsx
> +const dateFormatter = (start: Date, end: Date): string => {
위 리뷰 처럼 dateFormatter에서 millsecond를 받고 계산하는게 좋을 것 같습니다. 그리고 계산하는 함수는 따로 뺄 수도 있겠네요. 그리고 따로 뺀함수는 libs나 utils와 같은 디렉토리에 보관해서 다른 곳에서 쓸 수 있도록 하면 좋을 것 같습니다

2019-05-01 00:24 UTC, Joonmo-dev commented on daemaBnb/src/components/CustomDatePresenter.tsx
> +  color?: string;
디자인(airbnb)를 참고하면 버튼색이 모두 다르진 않습니다. 몇가지 색을 지정해놓는 편이 통일하는데 도움을 줄 수 있을 것 같네요.

2019-05-08 00:46 UTC, khg0712 commented on daemaBnb/src/components/CustomDatePresenter.tsx
> +  color?: string;
날짜는 거의 대부분 검은색으로 되어 있어서 그냥 검은색으로 통일할게요

2019-05-08 05:54 UTC, engolder requested changes

2019-05-08 05:54 UTC, engolder commented on daemaBnb/src/utils/formatDate.ts
> +export default formatDate;
default로 하는 것보다는 named로 내보내는 것이 좋을 것 같습니다.
formatDate같은 경우는 단일 함수만 포함하는 파일이기에 상관이없지만 만약 여러 함수를 표현하거나 클래스, 인터페이스 등을 포함하는 util파일이 있을 경우도 생각한다면 모두 named로 통일하는 편이 좋을 것 같아요!!

2019-05-08 06:04 UTC, khg0712 commented on daemaBnb/src/utils/formatDate.ts
> +export default formatDate;
아하 알겠습니당!!

2019-05-10 00:28 UTC, engolder approved these changes

2019-05-10 08:26 UTC, merged